### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by DrDuszek** [seba76/virtualbox4dsm#3]
Welcome

When will be my SYN 218+ have cpu intel Applo Lake work from VB.

**Comment by seba76** [comment]
Currently I'm supporting only syno's that are on kernel 3.10.x appolo lake has kernel 4.4.x 
Reason for that is I have no way to verify if it is working correctly since I don't have such box andI'm trying to limit number of arch since preparing and building those for new version is taking a lot of time.
