### ISSUE TITLE
USB issue

### ISSUE THREAD

**Issue by giter666** [seba76/virtualbox4dsm#6]
I installed virtualbox4dsm 6.0.8 on DSM 6.2-23739.
The DSM system sees devices connected to USB (lsusb also displays them)
Unfortunately, I can not provide USB devices to virtual machines.
VirtualBox does not detect devices.

![nd](https://user-images.githubusercontent.com/51287015/58759655-ccf2d680-852d-11e9-9fa8-0f22e2a01807.png)

How can I fix it ?

**Comment by seba76** [comment]
I didn't add script for handling USB devices, didn't have need to use it on 3615. I will update release with this script.

**Comment by ghost** [comment]
Thanks at first for creating the SPK's :-) !!!!!

Maybe at Line 114 in the installer script the file has to be renamed 50-virtualbox.rules. Otherwise it isn't executed by udevadm. Tested at DS1515+

**Comment by seba76** [comment]
This should not be the case. By spec all files with extension .rules are picked up. Number is used just to ensure order for rules definitions. What might be possible is that you have some rule that overrides rules from virtualbox.rules file. But in any case I will rename file and add prefix in my next build. To test this execute following command:
`udevadm test /dev/bus/usb/001/001`
you should  get a list of read rule files i.e. something like this

> calling: test
> version 204
> This program is for debugging only, it does not run any program
> specified by a RUN key. It may show incorrect results, because
> some values may be different, or not available at a simulation run.
> 
> error reading /etc/udev/hwdb.bin: No such file or directory
> load module index
> read rules file: /usr/lib/udev/rules.d/05-system-default.rules
> read rules file: /usr/lib/udev/rules.d/05-system-env.rules
> read rules file: /usr/lib/udev/rules.d/40-check-rdx.rules
> read rules file: /usr/lib/udev/rules.d/40-usb-env.rules
> read rules file: /usr/lib/udev/rules.d/45-update-disk-info.rules
> read rules file: /usr/lib/udev/rules.d/50-boot-flash.rules
> read rules file: /usr/lib/udev/rules.d/50-disk.rules
> read rules file: /usr/lib/udev/rules.d/50-firmware.rules
> read rules file: /usr/lib/udev/rules.d/50-hiddev.rules
> read rules file: /usr/lib/udev/rules.d/50-iscsi.rules
> read rules file: /usr/lib/udev/rules.d/50-mmc.rules
> read rules file: /usr/lib/udev/rules.d/50-net.rules
> read rules file: /usr/lib/udev/rules.d/50-printer-bus.rules
> read rules file: /usr/lib/udev/rules.d/50-printers.rules
> read rules file: /usr/lib/udev/rules.d/50-scsi.rules
> read rules file: /usr/lib/udev/rules.d/50-scsi_host.rules
> read rules file: /usr/lib/udev/rules.d/50-tty.rules
> read rules file: /usr/lib/udev/rules.d/50-ups.rules
> read rules file: /usr/lib/udev/rules.d/50-usb-bluetooth.rules
> read rules file: /usr/lib/udev/rules.d/50-usb-dvb.rules
> read rules file: /usr/lib/udev/rules.d/50-usb-modem.rules
> read rules file: /usr/lib/udev/rules.d/50-usb-wifi.rules
> read rules file: /usr/lib/udev/rules.d/50-usb.rules
> read rules file: /usr/lib/udev/rules.d/60-fix-plex-hw-transcoding.rules
> read rules file: /usr/lib/udev/rules.d/60-tv-butler-fix.rules
> read rules file: /usr/lib/udev/rules.d/virtualbox.rules
> rules contain 24576 bytes tokens (2048 * 12 bytes), 5201 bytes strings
> 477 strings (8850 bytes), 291 de-duplicated (3836 bytes), 187 trie nodes used
> unable to open device '/sys/dev/bus/usb/001/001'
> unload module index

**Comment by back0nline** [comment]
Did you implement the USB devices on the last version? Because i'm not able to see any USB

**Comment by seba76** [comment]
when you execute  **udevadm test /dev/bus/usb/001/001** do you get line like this?
**read rules file: /usr/lib/udev/rules.d/50-virtualbox.rules**
Also what do you get as output for:
**sudo /opt/VirtualBox/VBoxManage list usbhost**
and for
**sudo /opt/VirtualBox/VBoxManage list usbfilters**

**Comment by back0nline** [comment]
I get this:

> /opt/VirtualBox/VBoxManage list usbhost
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxManage)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxManage)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxDDU.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxRT.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxRT.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxXPCOM.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxXPCOM.so)
Host USB Devices:

>UUID:               a4f9024c-5123-468b-bcd5-c2b908a460f8
VendorId:           0xf400 (F400)
ProductId:          0xf400 (F400)
Revision:           1.0 (0100)
Port:               2
USB version/speed:  2/High
Manufacturer:       JetFlash
Product:            Mass Storage Device
SerialNumber:       L7SC54E1
Address:            sysfs:/sys/devices/pci0000:00/0000:00:13.2/usb2/2-3//device:/dev/vboxusb/002/002
Current State:      Busy

>UUID:               3cc2da35-80e9-4375-8b05-308f9bd86502
VendorId:           0xf400 (F400)
ProductId:          0xf400 (F400)
Revision:           1.0 (0100)
Port:               1
USB version/speed:  2/High
Manufacturer:       JetFlash
Product:            Mass Storage Device
SerialNumber:       AVRF4WT9
Address:            sysfs:/sys/devices/pci0000:00/0000:00:12.2/usb1/1-2//device:/dev/vboxusb/001/003
Current State:      Busy

>UUID:               0b3c23fa-539f-4c4b-aaa4-078a288d8efe
VendorId:           0x0451 (0451)
ProductId:          0x16a8 (16A8)
Revision:           0.9 (0009)
Port:               2
USB version/speed:  2/Full
Manufacturer:       Texas Instruments
Product:            TI CC2531 USB CDC
SerialNumber:       __0X00124B0018ED1103
Address:            sysfs:/sys/devices/pci0000:00/0000:00:12.0/usb4/4-3//device:/dev/vboxusb/004/002
Current State:      Busy

>/opt/VirtualBox/VBoxManage list usbfilters
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxManage)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxManage)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxDDU.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxRT.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxRT.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxXPCOM.so)
/opt/VirtualBox/VBoxManage: /lib/libstdc++.so.6: no version information available (required by /opt/VirtualBox/VBoxXPCOM.so)
Global USB Device Filters:

>none

>udevadm test /dev/bus/usb/001/001
calling: test
version 204
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

>error reading /etc/udev/hwdb.bin: No such file or directory
load module index
read rules file: /usr/lib/udev/rules.d/05-system-default.rules
read rules file: /usr/lib/udev/rules.d/05-system-env.rules
read rules file: /usr/lib/udev/rules.d/40-check-rdx.rules
read rules file: /usr/lib/udev/rules.d/40-usb-env.rules
read rules file: /usr/lib/udev/rules.d/45-update-disk-info.rules
read rules file: /usr/lib/udev/rules.d/50-boot-flash.rules
read rules file: /usr/lib/udev/rules.d/50-disk.rules
read rules file: /usr/lib/udev/rules.d/50-firmware.rules
read rules file: /usr/lib/udev/rules.d/50-hiddev.rules
read rules file: /usr/lib/udev/rules.d/50-iscsi.rules
read rules file: /usr/lib/udev/rules.d/50-mmc.rules
read rules file: /usr/lib/udev/rules.d/50-net.rules
read rules file: /usr/lib/udev/rules.d/50-printer-bus.rules
read rules file: /usr/lib/udev/rules.d/50-printers.rules
read rules file: /usr/lib/udev/rules.d/50-scsi.rules
read rules file: /usr/lib/udev/rules.d/50-scsi_host.rules
read rules file: /usr/lib/udev/rules.d/50-tty.rules
read rules file: /usr/lib/udev/rules.d/50-ups.rules
read rules file: /usr/lib/udev/rules.d/50-usb-bluetooth.rules
read rules file: /usr/lib/udev/rules.d/50-usb-dvb.rules
read rules file: /usr/lib/udev/rules.d/50-usb-modem.rules
read rules file: /usr/lib/udev/rules.d/50-usb-wifi.rules
read rules file: /usr/lib/udev/rules.d/50-usb.rules
read rules file: /usr/lib/udev/rules.d/50-virtualbox.rules
read rules file: /usr/lib/udev/rules.d/60-input-id-hassio.rules
read rules file: /usr/lib/udev/rules.d/60-serial-hassio.rules
rules contain 24576 bytes tokens (2048 * 12 bytes), 5783 bytes strings
528 strings (9594 bytes), 319 de-duplicated (4021 bytes), 210 trie nodes used
unable to open device '/sys/dev/bus/usb/001/001'
unload module index

**Comment by seba76** [comment]
when you do ** ls -al /dev/vboxusb/** you should get some folder(s) listed like:
_total 0
drwxr-x---  3 root root    60 Aug 27 08:48 .
drwxr-xr-x 14 root root 19180 Aug 27 09:21 ..
drwxr-x---  2 root root    80 Aug 27 09:21 001_

and in my case for  **ls -al /dev/vboxusb/001/** I get
_total 0
drwxr-x--- 2 root root     80 Aug 27 09:21 .
drwxr-x--- 3 root root     60 Aug 27 08:48 ..
crw-rw---- 1 root root 189, 3 Aug 27 08:48 004
crw-rw---- 1 root root 189, 4 Aug 27 09:21 005_

this means script is working. However it appears to be some kind of problem in phpVirtualbox and it gives error when trying to add usb filters/devices this means you would need to use **/opt/VirtualBox/VBoxManage** to add usb to VM, consult Virtualbox documentation on how to do that.
